import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        <div className="min-h-screen flex flex-1">
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
